# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsmc.proto\"N\n\rsetupProposal\x12\r\n\x05nonce\x18\x01 \x01(\x04\x12\x16\n\x0eminRefundBlock\x18\x02 \x01(\x04\x12\x16\n\x0eManRefundBlock\x18\x03 \x01(\x04\"\x18\n\tsignature\x12\x0b\n\x03sig\x18\x01 \x01(\x0c\"\x1b\n\x0b\x66undingTxID\x12\x0c\n\x04txid\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUPPROPOSAL._serialized_start=13
  _SETUPPROPOSAL._serialized_end=91
  _SIGNATURE._serialized_start=93
  _SIGNATURE._serialized_end=117
  _FUNDINGTXID._serialized_start=119
  _FUNDINGTXID._serialized_end=146
# @@protoc_insertion_point(module_scope)
